version: '3.8'

services:
  app:
    container_name: laravel
    image: laravel-app
    build:
      context: .
      dockerfile: .develop/Dockerfile
    volumes:
      - .:/srv/app
    ports:
      - 8088:80

# postgres_data volume is removed since it is no longer needed

# docker-compose build
# docker-compose up

# home image:
# sha256:4075adcf8dcf3db54f8c790617d1c8f2391d3bba76b379e59a3183d452181f3d

# w image: