version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel_app
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=${APP_ENV}
      - APP_KEY=${APP_KEY}
      - APP_DEBUG=${APP_DEBUG}
      - APP_URL=${APP_URL}
    volumes:
      - .:/var/www/html
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge

# postgres_data volume is removed since it is no longer needed

# docker-compose build
# docker-compose up

# home image:
# sha256:4075adcf8dcf3db54f8c790617d1c8f2391d3bba76b379e59a3183d452181f3d

# w image:
