version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel_app
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      APP_ENV: local
      APP_KEY: base64:your-app-key
      APP_DEBUG: "true"
      APP_URL: http://localhost
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: your_database_name
      DB_USERNAME: your_username
      DB_PASSWORD: your_password
    volumes:
      - .:/var/www/html
    networks:
      - laravel_network
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: public
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345678
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge

volumes:
  postgres_data:

# home image:
# sha256:4075adcf8dcf3db54f8c790617d1c8f2391d3bba76b379e59a3183d452181f3d